### PR TITLE
FIX: Fix generate_custom_images.py

### PR DESCRIPTION
**Pull request by jrmlhermitte**
I needed to make these two changes to get this script to work on my machine:
1. indentation issue
2. Give a default to 'family' to be `''` and not `None`

### CODE REVIEW

**Comment by jrmlhermitte** [comment]
PS: Please let me know if this is the right way to fix this, and how to do this. I'm very new to this.

My main motivation is that I need to create a spark cluster on google cloud that has python installed with specific libraries. If there is a better way I'd be open to hearing it thanks!

**Comment by aniket486** [comment]
Thanks for catching this. Please sign the CLA so that we can merge your changes.

**Comment by aniket486** [comment]
The fix for indentation issue was submitted with #64 .

**Comment by jrmlhermitte** [comment]
What about the '--family' default? Can you please put that in? It doesn't have to be this pr.else explain why this is not correct. Thanks!

**Comment by medb** [comment]
It's fixed too: https://github.com/GoogleCloudPlatform/cloud-dataproc/blob/34b3f028a301bdae9c5233b9e78cf39d0b47b59a/custom-images/generate_custom_image.py#L307

**Pull request closed without merging**
